# DOCKER-COMPOSE file is used to define and run multi-container Docker applications

services:

  # MARIADB ----------------------------------------------------------------------------
  # this container does not depend on any other, so it should be the first to be created

  mariadb:
    # service name
    container_name: mariadb
    # relative location of Dockerfile used to build the Docker image for mariadb service; 
    # defines the build process for Docker image
    build: ./requirements/mariadb/
    # location where mariadb DB files will be stored;
    # ensures that data persists across container restarts
    # volume that maps a named volume 'database' to the directory /var/lib/mysql/ inside the container
    volumes:
      - database:/var/lib/mysql/
    # network(s) joined by mariadb
    # the all network should be defined elsewhere in this Docker Compose file
    networks:
      - all
    # runs the setup.sh (initialization) shell script before starting the main process of the container
    init: true
    # restarts the container when a failure occur (if it exits with a non-zero code) - restart policy
    restart: on-failure
    # file from which to read environment variables
    env_file:
      - .env

  # WORDPRESS --------------------------------------------------------------------------
  # this container depends exclusively on mariadb cmariadb:
    # service name
    container_name: mariadb
    # location of the container mariadb; defines the build process for Docker image
    build: ./requirements/mariadb/
    # location where DB files will be saved
    volumes:
      - database:/var/lib/mysql/
    # network used by mariadb
    networks:
      - all
    # runs the setup.sh shell script 
    init: true
    # restarts the container when a failure occur
    restart: on-failure
    # file in which the environment variables can be found
    env_file:
      - .env
ontainer, so it should start next

  wordpress:
    # service name
    container_name: wordpress
    # relative location of Dockerfile used to build the Docker image for wordpress service; 
    # defines the build process for Docker image
    build: ./requirements/wordpress/
    # location where wordpress DB files will be stored;
    # ensures that data persists across container restarts;
    # volume that maps a named volume 'wpfiles' to the directory /var/www/inception/ inside the container
    volumes:
      - wpfiles:/var/www/inception/
    # network(s) joined by wordpress
    # the all network should be defined elsewhere in the Docker Compose file
    networks:
      - all
    # runs the setup.sh (initialization) shell script before starting the mains process of the container
    init: true
    # restarts the container when a failure occur (if it exits with a non-zero code) - restart policy
    restart: on-failure
    # file from which to read environment variables
    env_file:
      - .env
    # all container dependencies for wordpress; 
    # indicates that this container does not start before the mariadb container is running
    depends_on:
      - mariadb

  # NGINX ------------------------------------------------------------------------------
  # this container depends on the wordpress container, so it should start next;
  # uses args to pass the certificate and key path to the Dockerfile
  # in the build moment with show the private informations that where in the .env file
  
  nginx:
    # service name
    container_name: nginx
    # defines the build process for Docker image
    build:
      # specifies the directory containing the Dockerfile and other importante files from the nginx container
      context: ./requirements/nginx/
      # the args sub-section allows passing build-time variables to the Docker build process
      # this variables are referenced in the Dockerfile using  ARG instructions
      args:
        # this variables values are taken from the environment
        # these arguments are usually used to configure SSL certificates and other setting necessary for the nginx service
        CERT_FOLDER: ${CERT_FOLDER}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    ports:
      - '443:443'
    # location where DB files will be saved
    volumes:
      - wordpress_files:/var/www/inception/
    # network used by nginx
    networks:
      - all
    init: true
    # restarts the container when a failure occur
    restart: on-failure
    # file in which the environment variables can be found
    env_file:
      - .env
    # all container dependencies for nginx;
    # indicates that this container does not start before the wordpress container is running
    depends_on:
      - wordpress

# volumes --------------------------------------------------------------------

# keeps the data shared between the containers
# it acts like a shared hard drive between the containers and the host machine
# device: where the data will be stored in the host machine
volumes:

  # keeps the database
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database

  # keeps the wordpress files
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress_files

# networks --------------------------------------------------------------------

# this network is used to connect the containers
# it acts like a virtual switch between the containers
# all is the name of the network
# bridge is the type of the network
networks:
  all:
    driver: bridge
