services:

  # MARIADB ----------------------------------------------------------------------------
  # this container does not depend on any other, so it should be the first to be created

  mariadb:
    container_name: mariadb
    # location of the container mariadb
    build: ./requirements/mariadb/
    # location where DB files will be saved
    volumes:
      - database:/var/lib/mysql/
    # network used by mariadb
    networks:
      - all
    # runs the setup.sh shell script 
    init: true
    # restarts the container when a failure occur
    restart: on-failure
    # file in which the environment variables can be found
    env_file:
      - .env

  # WORDPRESS --------------------------------------------------------------------------
  # this container depends exclusively on mariadb container, so it should start next

  wordpress:
    container_name: wordpress
    # location of the container wordpress
    build: ./requirements/wordpress/
    # location where DB files will be saved
    volumes:
      - wordpress_files:/var/www/inception/
    # network used by wordpress
    networks:
      - all
    # runs the setup.sh shell script
    init: true
    # restarts the container when a failure occur
    restart: on-failure
    # file in which the environment variables can be found
    env_file:
      - .env
    # all container dependencies for wordpress; 
    # indicates that this container does not start before the mariadb container is running
    depends_on:
      - mariadb

  # NGINX ------------------------------------------------------------------------------
  # this container depends on the wordpress container, so it should start next;
  # uses args to pass the certificate and key path to the Dockerfile
  # in the build moment with show the private informations that where in the .env file
  
  nginx:
    container_name: nginx
    # location of the container nginx
    build:
      context: ./requirements/nginx/
      args:
        CERT_FOLDER: ${CERT_FOLDER}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    ports:
      - '443:443'
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

# volumes --------------------------------------------------------------------

# keeps the data shared between the containers
# it acts like a shared hard drive between the containers and the host machine
# device: where the data will be stored in the host machine
volumes:

  # keeps the database
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database

  # keeps the wordpress files
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress_files

# networks --------------------------------------------------------------------

# this network is used to connect the containers
# it acts like a virtual switch between the containers
# all is the name of the network
# bridge is the type of the network
networks:
  all:
    driver: bridge
